CREATE DATABASE IF NOT EXISTS wordpress;

CREATE USER IF NOT EXISTS 'oessamdi'@'%' IDENTIFIED BY '12345679';
GRANT ALL PRIVILEGES ON wordpress.* TO 'oessamdi'@'%';
FLUSH PRIVILEGES;


ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
FLUSH PRIVILEGES;
